### ISSUE TITLE
BUG lors d'un bouclage quid du TLC / TLI !

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-controle#123]

**Comment by Guillaume35** [comment]
Ce bug vient certainement de l'API : lorsqu'un bouclage est réalisé,
l'infor "previous_id" est envoyé à l'API. Dans ce cas de figure, l'API
réalise une copie des informations de la previous collecte. Au moment ou ce
développement a été fait, il n'y avait pas de TLC et TLI utilisé sur les
collectes (InformationLiaison). Il faut donc aller modifier la fonction
d'API qui gère ce cas de figure afin que le TLC TLI soit bien copiés sur la
nouvelle collecte.

--
Guillaume Modard
06 72 44 44 17


Le ven. 23 juin 2023 à 14:59, Killian KOPP ***@***.***> a
écrit :
