### ISSUE TITLE
Lors de la programmation d'un bouclage, la liste des opérateurs est vide et l'opérateur à bouclé n'est pas sélectionné

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#129]
**Description :**
Dans la vue consultation, lors du clique sur le bouton bouclage, la modal de programmation s'ouvre. La liste des opérateurs ne semble pas se charger et reste vide. Du coup, l'opérateur à contrôlé n'est pas sélectionné.

Malgré tout, en cliquant sur "Enregistrer", le bouclage est malgré tout créé et affecté au bon opérateur. Il s'agit donc d'une erreur à l'affichage.

**Niveau de bug :** fonctionnel

![Screenshot from 2023-06-29 10-33-33](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/258a327d-969e-4263-bb2d-466368a720ee)

**Comment by marilehoux** [comment]
@Guillaume35   résolu dans pull request bug-navigation-bouclage
