### ISSUE TITLE
Ajouter les icons Kn², bouclage KN fais... dans la consultation

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#148]
**Description :**
Lors de la consultation des KNs, la liste de gauche doit afficher les pictos suivants :

- KN de KN (Kn²) (à venir)
- Bouclage réalisé avec la couleur bouclée et le nb de jours (following_id + following_result renseigné)
- Bouclage programmé mais non terminé avec le nb de jour (following_id renseigné + following_result null)
- Bouclage non réalisé sur une note M et I ((result_var == M || result_var == I) && following_id null)

Un espace doit être prévu sur l'Item de liste pour ajouter ces icons d'état.

![Screenshot from 2023-07-18 09-35-24](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/5c1c5bd5-42cf-48fc-9a07-9a2b3445af7a)

![Capture d’écran 2023-07-12 à 00 53 05](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/eea62d12-1c45-4473-ba4a-9e7587b74a22)

**Comment by deathtroll22** [comment]
Je pars sur quelle branche ?
