### ISSUE TITLE
Consultation : Le nombre d'items évalué est faux

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#175]
**Description**
Dans la vu consultation, il semble que le nb d'items évalués prennent en compte des metas champs en fin de questionnaire (dans la section importation)

Ce compteur étant calculé et stocké en base de données, il est enregistré faux.

**Élément de résolution**
- Lister les formulaires contenant les champs importation
- Créer une requête de mise à jour pour supprimer les métas-champs des formulaires concerner
- Créer une requête de mise à jour pour recalculer les totaux

A plus long terme, le champs total évalué n'a pas besoin d'être stockée en base de données. Il pourrait être le résultat d'un champ calculé sur une jointure.

![Screenshot from 2023-07-25 11-44-34](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/25234607-dbea-40bd-8cf5-a0dc6b4e6a42)
![Screenshot from 2023-07-25 11-44-43](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/2378c547-18eb-4a7f-960d-5c39e00bd820)

**Comment by killiankopp** [comment]
Suppression des blocs d'import (corbeille = OUI)
Suppression des linges d'import (corbeille = OUI)
Suppression des informations d'import (corbeille = OUI)
Recalcul du nb de question
Recalcul du nb de réponse

OK (fait en requete rien à commit)
