### ISSUE TITLE
Consultation : En mode modification, la liste du personnel est limité aux 50 premiers

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#201]
**Description**

- [x ] La liste du personnel en mode modification renvoie uniquement les 50 premiers résultats. 

- [x ] Il est nécessaire de pouvoir sélectionner n'importe quelle personne de la liste.

De plus, lorsque l'opérateur est modifié, il faut que l'API rattache automatiquement le contrôle à l'habilitation du personnel concerné.

mkg_information__liaison.tlc = "CharacteristicPersonnel"
mkg_information__liaison.tli = L'ID de la characteristic personnel qui correspond à ce contrôle sur ce personnel.

**Criticité** Bloquant

**Élément de résolution**
Passer un paramètre de limit aucune à l'API.

![Screenshot from 2023-08-01 08-59-36](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/6260e46b-3940-4be0-adb8-598ad33b2754)

**Comment by TigrouForMatic** [comment]
API --> pull request
