### ISSUE TITLE
Consultation : Après modification, les réponses aux questions disparaissent

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#202]
**Description**
Lors de l'utilisation de la fonction modifier, les blocs et les questions disparaissent lors de l'enregistrement.
Par la même, les informations sur la liste à gauche ne sont pas actualisées.

**Criticité** Fonctionnel

**Élément de résolution**
Mettre à jour uniquement les trois informations modifiables sur le store plutôt que de remplacer l'ensemble de la collecte. En effet, la collecte est chargée avec des données étendues. Le retour d'information en mode modification ne renvoie que les données primaires de la collecte ce qui fait disparaître les questions et les réponses.

![Screenshot from 2023-08-01 09-04-48](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/a2ce0e47-2120-44cb-9609-21069b5bd35f)

**Comment by TigrouForMatic** [comment]
Pull request : Debug : disparition des questions lors de la modification de la collecte dans la consultation #214
