### ISSUE TITLE
Statistique : gérer le resize de la page

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#211]
**Description**
Lorsque la fenêtre est redimensionnée, les graphiques sortent de la vue.
De plus, l'ensemble des cards n'ont pas les même proportions en largeur.

**Éléments de résolution**
Observer l'événement "resize" de document pour re-générer les graphiques.
Intégrer l'ensemble des cards à l'intérieur du même container.

![Screenshot from 2023-08-01 14-34-07](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/f00b9cfe-6248-4130-9663-c63e739ace45)

![Screenshot from 2023-08-01 14-36-53](https://github.com/pebble-solutions/App-QSE-controle/assets/945411/50b25286-57ef-42a4-a3dd-08bbe3dc08d9)

**Comment by deathtroll22** [comment]
j'ai revu les l'affichage mais face au vu du nombre restreint de personnes accedant à statistiques, j'ai mis de coté les reglages du googlechart pour l'agenda
