### ISSUE TITLE
différence de compteur dans les listes de contrôles programmé et terminé

### ISSUE THREAD

**Issue by marilehoux** [pebble-solutions/App-QSE-controle#32]
![Capture d’écran de 2023-01-06 09-45-08](https://user-images.githubusercontent.com/88326618/210965339-2d8aa416-f3b7-4e9c-9d2f-397dbab56280.png)

**Comment by killiankopp** [comment]
Bug de l'api. revoir le ticket ouvert par Guillaume pour plus de détail

**Comment by killiankopp** [comment]
**Roles**
Dev Team : @marilehoux
