### ISSUE TITLE
RQSE : afficher des statistiques -> consulter rapidement les informations

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#47]
**customer and user**
FE - RQSE

**Scrum brief**
En tant que RQSE, je veux filtrer la vue consultation afin de rapidement trier les informations que je consulte et les comparer les unes aux autres

**Brief**

**Additional information**
Add any other context or screenshots about the issue here.

**Roles**
- design team :  
- dev team : 

**Code indication**
Liste des filtres à ajouter :

- Tous les contrôles
- Grouper par questionnaire
- Groupe par projet

Pour chaque filtre, il doit être possible de définir une date de début et une date de fin de recherche des collectes.

Consulter les spécifications :
https://docs.google.com/document/d/1ufEFKIm5scNjboNX69Z0oFZmLiqax76qP7CXP9fsCTE/edit#heading=h.jxve1riw58kn

**Todo**
- [ ] @ :

**Comment by marilehoux** [comment]
ok pour les filtres par date, formulaire, et projets. consultation des projets dans la vue principale.

- les requêtes sont effectuées  sans limite pour le moment sinon incohérences avec le store.
- les champs de recherche ou de sélection sont immédiatement réactifs
push le 03/02

**Comment by marilehoux** [comment]
dans la liste "tous les controles" reste a gerer l'affichage par date reverse

**Comment by glesaout** [comment]
Il faudrait ajouter sur : mkg/motor/information/options/CollecteListeOptions.php :
- orderby (date, date_done, id)
- orderby_direction (ASC, DESC
