### ISSUE TITLE
Unifier les libellés "Opérateur non renseigné"

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#59]
Remplacer les libellé "Personnel non-définit" par "Opérateur non renseigné" ou par "Contrôleur non renseigné" afin d'unifier l'interface.

![Screenshot from 2023-02-27 12-03-35](https://user-images.githubusercontent.com/945411/221547324-b53c0685-6f14-4e06-97bf-08f017c4abc0.png)

**Comment by marilehoux** [comment]
@Guillaume35  ok unifié sur branche feat-controle-veille
