### ISSUE TITLE
En tant que contrôleur, je veux pouvoir accéder à la chaîne complète des contrôles afin de consulter l'historique des contrôles

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/App-QSE-controle#71]
**Brief**
Lorsqu'un contrôle est créé à la suite d'un autre contrôle, les champs suivant sont utilisés afin de tracer de manière montante ou descendante l'enchaînement des contrôles.

Par exemple, un KN est réalisé mais l'opérateur obtient un I, un nouveau KN est alors programmé dans un délai de 7 jours. Le contrôleur a besoin de retrouver rapidement le KN initial qui a amené à créer le nouveau KN qui est en train d'être réalisé.

**Code indication**

| Colonne | Type de donnée | fk | Description |
| --- | --- | --- | --- |
| previous_id | INT | mkg_information__liaison(id) | ID de la collecte (InformationLiaison) précédente |
| following_id | INT | mkg_information__liaison(id) | ID de la collecte (InformationLiaison) suivante |

**Comment by Guillaume35** [comment]
Le framework pebble-ui est mis à jour afin de permettre la configuration de la barre d'outils en pied de page.

Exemple d'utilisation

```
<ToolbarFooter wrapper-class="px-2 py-1 border-top border-dark" class-name="bg-dark">
    <div class="d-flex justify-content-between align-items-center">
        <button class="btn btn-secondary">Bouton à gauche</button>
        <button class="btn btn-primary">Bouton à droite</button>
    </div>
</ToolbarFooter>
```

Résultat : 

![Screenshot from 2023-03-24 08-33-50](https://user-images.githubusercontent.com/945411/227454676-8b32591f-c642-4414-9659-a37ba25cf2ec.png)

**Comment by Guillaume35** [comment]
Les collectes renvoient deux nouvelles informations :

| Champ | Type | Valeur |
| --- | --- | --- |
| previous_result | ?string | La note globale de la collecte précédente ou null |
| following_result | ?string | La note globale de la collecte suivante ou null |
