### ISSUE TITLE
Id de Opérateur Ambre GAVEAU différent de l'id Controleur Ambre GAVEAU

### ISSUE THREAD

**Issue by heligonSeb** [pebble-solutions/App-QSE-controle#78]
l'id de au niveau du select opérateur semble erroné car il affiche Lionel FAGOT apres validation 
![2023-03-27_15-29](https://user-images.githubusercontent.com/52566459/227955892-f357dbaa-3562-4883-a203-f2ce79f9cfd5.png)

**Comment by Guillaume35** [comment]
Je ne parvient pas à reproduire le bug. Pouvez vous me communiquer plus d'éléments de contexte ?

**Comment by Guillaume35** [comment]
Après discussion avec Sebastien, il semble que certains travaillent trop !
