### ISSUE TITLE
Annuler un contrôle programmé

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#9]
Permettre d'annuler un contrôle programmé. Un contrôle annulé s'affiche dans la programmation et est notifié dans l'interface. Il ne s'affiche pas en contrôle.

**Comment by killiankopp** [comment]
Note attention à ce que ça ne gêne pas la veille !

**Comment by killiankopp** [comment]
Utiliser la commande supprimer et non annuler
