### ISSUE TITLE
Responsable : créer un contrôle de veille lorsque je consulte un contrôle de bouclage afin de ne pas oublier

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#92]
**Scrum brief**
Dans la vue consultation, lorsque le responsable consulte un contrôle, il faudrait lui donner la possibilité de lancer un contrôle de veille. Le contrôleur peut déjà le faire à l'issue de son contrôle.

**Brief**
Ajouter un bouton "+" à droite de la timeline lorsqu'il n'y a pas de following_id. Le clique sur le bouton déclenche la route suivante : /consultation/:id/new

La vue de programmation de contrôle se charge avec les champs pré-remplis, le contrôleur est déjà pré-sélectionné mais le responsable peut le modifier.

**Additionnal**

Pour récupérer la branche de développement de cette fonction :

```
git fetch origin
git checkout feat-controle-veille
```

Renvoyer sur le dépôt :

`git push origin feat-controle-veille`

**Comment by marilehoux** [comment]
![image](https://user-images.githubusercontent.com/88326618/231093963-dbce4818-b427-4c7d-9439-b21d92198c14.png)

**Comment by marilehoux** [comment]
une fois le contrôle de veille programmé. La vue du contrôle futur dans le menu consultation est celle ci-dessus. Le responsable peut donc encore programmer une veille alors que le contrôle n'est pas encore réalisé.
dois-je prévoir un blocage au niveau de la vue?

**Comment by Guillaume35** [comment]
Yes, on ne peut pas programmer une veille sur un contrôle non finalisé

**Comment by Guillaume35** [comment]
Quelques modifs à voir :

- Il ne faut pas pouvoir modifier le type de KN lors de la programmation d'une veille par la vue consultation. Les autres infos sont modifiables
- Lors de la validation de la veille, le message devrait être "Contrôle de veille programmé".
- Lors de la consultation d'un contrôle non terminé, si l'utilisateur connecté est le contrôleur, il faudrait ajouter un bouton "Lancer le contrôle".

**Comment by marilehoux** [comment]
@killiankopp @Guillaume35 
contrôle de veille dans ce cas équivaut à **bouclage.**
le contrôleur peut (et devrait) programmer un contrôle de bouclage si le contrôle n'est pas évalué S ou A

si le contrôle est évalué S ou M, il ne peut pas programmer de contrôle de bouclage. 

Seule la dernière note apparaît dans le suivi habilitation ou toute la chaîne?

**Comment by marilehoux** [comment]
Je vois avec équipe chargé d'affaire si le terme **bouclage** est à reprendre dans l'appli pour éviter l'utilisation du terme veille  déjà utilisé pour les KN de KN et la programmation automatique pour assurer le maintien de l'habilitation
