### ISSUE TITLE
Aucune réponse enregistrée à la fin d'un contrôle

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle#94]
**Description**

À la sortie du contrôle, l'alerte "Aucune réponse enregistrée" est retournée.

En cliquant sur "Précédent" et "Suivant" à nouveau, l'erreur disparaît et le bon nombre d'éléments est retourné.

**Niveau d'erreur**

Affichage uniquement. Pas de blocage du fonctionnement, pas d'enregistrement erroné sur le serveur.

![Screenshot from 2023-04-07 10-37-55](https://user-images.githubusercontent.com/945411/230589319-090b1506-f719-4d43-9fbf-0a0dfb86c814.png)

**Comment by marilehoux** [comment]
![image](https://user-images.githubusercontent.com/88326618/233415177-2e86e782-b9a2-4aa7-ba52-fd0ff2ec0639.png)

**Comment by marilehoux** [comment]
bug corrigé sur version "unstable"
